[project]
name = "tests"
version = "0.1.0"
description = "Python tests exploration"
authors = [
    {name = "diego", email = "diegoariel83@gmail.com"},
]
dependencies = [
    "psycopg>=3.2.3",
]
requires-python = "==3.12.*"
readme = "README.md"

[tool.pdm]
distribution = false

# does uv support this?
[tool.pdm.scripts]
tests = "pdm run pytest" # uv sync --all-extra ; uv run pytest
lint = "pdm run ruff check ." # uv run mypy .

[dependency-groups]
dev = [
    "pytest>=8.3.2",
    "pytest-mock>=3.14.0",
    "testcontainers>=4.8.2",
    "typing-extensions>=4.12.2",
]
lint = [
    "ruff>=0.7.4",
]
test = [
    "coverage>=7.6.7",
    "pytest-cov>=6.0.0",
]
