[project]
name = "tests"
version = "0.1.0"
description = "Python tests exploration"
authors = [
    {name = "diego", email = "diegoariel83@gmail.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"


[project.optional-dependencies]
dev = [
    "typing-extensions>=4.12.2",
    "pytest>=8.3.3",
    "pytest-mock>=3.14.0",
]
[tool.pdm]
distribution = false

[tool.pdm.scripts]
tests = "pdm run pytest"
lint = "pdm run mypy ."
