name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4.1
        with:
          python-version: 3.12
          cache: true

      - name: Install dependencies
        run: pdm sync --dev --group test --group dev

      - run: pdm lint
      - run: pdm tests
