name: Tests (uv)

on: [push]

jobs:
  tests-uv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        id: setup-uv
        uses: astral-sh/setup-uv@v3.2.3
        with:
          version: 0.5.2
          enable-cache: true

      #- name: Set up Python
      #  run: uv python install

      # it might be faster as github runner caches it
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: uv sync --frozen --all-extras --dev

      - run: uv run ruff check .
      - run: uv run pytest

      # not needed according to the docs
      #- if: steps.setup-uv.outputs.cache-hit != 'true'
      #  run: uv cache prune --ci