name: Tests (pdm)

on:
  workflow_dispatch:


jobs:
  tests-pdm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4.1
        with:
          python-version-file: .python-version
          cache: true

      - name: Install dependencies
        run: pdm sync --dev --group test --group dev --group lint

      - run: pdm lint
      - run: pdm tests
